version: '3'
services:
  laravel-server:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - VARIANT=redis
      - INSTALL_NODE=true
      - NODE_VERSION=lts/*
